version: '2.12.1'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
  db:
    image: postgres:15
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"