version: '2.12.1'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-jmz9$$#gv1mw9e91#8%6659--nlc^_j=(bv8adu$1p$#cbqzo7f"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:15
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"